
import React, { useState, useEffect, useRef, useMemo, useCallback } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Avatar, AvatarFallback } from '@/components/ui/avatar';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog";
import {
    Mic, MicOff, Phone, BrainCircuit, Loader2, Volume2,
    VolumeX, RefreshCw, Square, MessageSquare, ChevronLeft,
    ChevronRight, Globe, Users, Filter, BookOpen, Sparkles, UserCheck, ArrowLeft, X, Bot, Calendar, Clock, BarChart,
    Mail, Building2, AlertTriangle, Target, Brain, CheckCircle, User as UserIcon, Eye, Plus, Search, BarChart3
} from 'lucide-react';
import { toast } from 'sonner';
import { aiRoleplay } from '@/api/functions';
import { RoleplaySession } from '@/api/entities';
import { RoleplayBot } from '@/api/entities';
import { Link, useNavigate, useLocation } from 'react-router-dom';
import { createPageUrl } from '@/utils';
import { format, formatDistanceToNow } from 'date-fns';
import AIRoleplayInsights from '@/components/roleplay/AIRoleplayInsights';
import { InvokeLLM } from '@/api/integrations';
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { User } from '@/api/entities';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Input } from '@/components/ui/input';
import { supabase } from '@/lib/supabase';
import { Checkbox } from '@/components/ui/checkbox';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { resolveElevenLabsVoiceId } from '@/utils/voiceMapping';

const MATERIAL_CATEGORIES = [
    'Product Knowledge', 'Sales Methodology', 'Objection Handling',
    'Discovery Questions', 'Closing Techniques', 'Industry Knowledge',
    'Compliance', 'Case Studies', 'General Training'
];

// New Sidebar component for live call assistance
const CallAssistantSidebar = ({ prospect }) => {
    // These "dos" and "donts" are currently static based on the provided outline.
    // In a real application, these could be dynamically generated by an AI based on the prospect's profile.
    const dos = [
        `Acknowledge ${prospect.name}'s team's current tools and processes.`,
        "Focus on how your solution integrates with existing systems.",
        "Highlight data-driven benefits.",
        "Encourage open dialogue and questions.",
        "Be clear about mutual benefits.",
    ];

    const donts = [
        "Don't dismiss their current setup.",
        "Avoid overly technical jargon unless prompted.",
        "Don't push for a decision too quickly.",
        "Avoid making promises you can't keep.",
    ];

    return (
        <div className="w-96 bg-slate-50 border-r border-slate-200 p-6 flex flex-col gap-6 overflow-y-auto h-full">
            <h3 className="text-xl font-bold text-slate-800 flex items-center gap-2">
                <BrainCircuit className="w-6 h-6 text-purple-600" />
                Live Sales Assistant
            </h3>

            <Card className="bg-white">
                <CardHeader>
                     <CardTitle className="text-base">Talking Points</CardTitle>
                </CardHeader>
                <CardContent>
                    <Tabs defaultValue="dos">
                        <TabsList className="grid w-full grid-cols-2">
                            <TabsTrigger value="dos">Dos</TabsTrigger>
                            <TabsTrigger value="donts">Don'ts</TabsTrigger>
                        </TabsList>
                        <TabsContent value="dos" className="pt-4">
                            <ul className="space-y-3">
                                {dos.map((item, i) => (
                                    <li key={i} className="flex items-start gap-2 text-sm text-slate-700">
                                        <div className="w-1.5 h-1.5 bg-green-500 rounded-full mt-1.5 flex-shrink-0"></div>
                                        {item}
                                    </li>
                                ))}
                            </ul>
                        </TabsContent>
                        <TabsContent value="donts" className="pt-4">
                             <ul className="space-y-3">
                                {donts.map((item, i) => (
                                    <li key={i} className="flex items-start gap-2 text-sm text-slate-700">
                                        <div className="w-1.5 h-1.5 bg-red-500 rounded-full mt-1.5 flex-shrink-0"></div>
                                        {item}
                                    </li>
                                ))}
                            </ul>
                        </TabsContent>
                    </Tabs>
                </CardContent>
            </Card>

            <Card className="bg-white">
                <CardHeader><CardTitle className="text-base">Negotiating & Closing</CardTitle></CardHeader>
                <CardContent className="space-y-2 text-sm">
                    <p className="font-semibold text-slate-700">The secret to closing fast:</p>
                    <p className="text-slate-600">Emphasize the efficiency and integration benefits for the team.</p>
                </CardContent>
            </Card>

            <Card className="bg-white">
                <CardHeader>
                    <CardTitle className="text-base">Key Prospect Info</CardTitle>
                </CardHeader>
                <CardContent className="text-sm space-y-3">
                    <div>
                        <p className="font-medium text-slate-500">Personality</p>
                        <p className="text-slate-800">{prospect.personality}</p>
                    </div>
                    <div>
                        <p className="font-medium text-slate-500">Key Pain Points</p>
                        <div className="flex flex-wrap gap-1 mt-1">
                            {prospect.painPoints?.map((pain, i) => <Badge key={i} variant="outline" className="text-xs bg-red-50 border-red-200 text-red-800">{pain}</Badge>)}
                        </div>
                    </div>
                </CardContent>
            </Card>
        </div>
    );
};


// Call in progress component with conversational flow
const CallInProgress = ({ prospect, onEndCall, onAnalysisComplete, knowledgeMaterialIds = [] }) => {
    const [callStatus, setCallStatus] = useState('connecting');
    const [transcript, setTranscript] = useState([]);
    const transcriptRef = useRef(transcript); // Ref to hold the latest transcript for stable callbacks
    const [isAIResponding, setIsAIResponding] = useState(false);
    const [isListening, setIsListening] = useState(false);
    const [isSpeaking, setIsSpeaking] = useState(false);
    const [isMuted, setIsMuted] = useState(false);
    const [isAudioMuted, setIsAudioMuted] = useState(false);
    const [isSidebarOpen, setIsSidebarOpen] = useState(true); // State for sidebar
    const audioPlayer = useRef(null);
    const recognition = useRef(null);
    const messagesEndRef = useRef(null);
    const conversationState = useRef('idle'); // 'idle', 'ai_speaking', 'user_listening'
    const callStartTime = useRef(null); // Added: To track call duration
    const audioContext = useRef(null); // Added: As per outline, for audio context management
    const currentAudioPromise = useRef(null); // Track current audio playback promise

    // Update transcriptRef whenever transcript state changes
    useEffect(() => {
        transcriptRef.current = transcript;
    }, [transcript]);

    const scrollToBottom = () => {
        messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
    };

    useEffect(scrollToBottom, [transcript]);

    const startListening = useCallback(() => {
        if (recognition.current && conversationState.current === 'idle' && !isMuted) {
            try {
                recognition.current.start();
            } catch (e) {
                // Ignore DOMException if recognition is already started
                if (e.name !== "InvalidStateError") {
                    console.error("Error starting speech recognition:", e);
                }
            }
        }
    }, [isMuted]);

    const playAudio = useCallback((audioBase64) => {
        // Skip audio playback if no audio is provided
        if (!audioBase64) {
            setIsSpeaking(false);
            conversationState.current = 'idle';
            return;
        }

        try {
            // Stop any currently playing audio first
            if (audioPlayer.current) {
                // Cancel any pending play promise
                if (currentAudioPromise.current) {
                    currentAudioPromise.current.catch(() => {}); // Ignore any errors from cancelled promise
                    currentAudioPromise.current = null;
                }
                audioPlayer.current.pause();
                audioPlayer.current.currentTime = 0;
            }

            const audioSrc = `data:audio/mpeg;base64,${audioBase64}`;
            audioPlayer.current = new Audio(audioSrc);
            conversationState.current = 'ai_speaking';

            // Set up event handlers before playing
            audioPlayer.current.onplay = () => setIsSpeaking(true);
            audioPlayer.current.onended = () => {
                setIsSpeaking(false);
                conversationState.current = 'idle';
                currentAudioPromise.current = null;
            };
            audioPlayer.current.onerror = (error) => {
                console.warn("Audio playback error:", error);
                setIsSpeaking(false);
                conversationState.current = 'idle';
                currentAudioPromise.current = null;
            };

            // Respect audio mute state
            audioPlayer.current.muted = isAudioMuted;

            // Start playback and track the promise
            currentAudioPromise.current = audioPlayer.current.play();

            currentAudioPromise.current
                .then(() => {
                    // Audio started successfully
                    console.log("Audio playback started successfully");
                })
                .catch((error) => {
                    // Handle play interruption or other errors gracefully
                    if (error.name === 'AbortError') {
                        console.log("Audio playback was interrupted - this is normal");
                    } else if (error.name === 'NotAllowedError') {
                        console.warn("Audio playback blocked - user interaction may be required");
                        toast.warning("Click anywhere to enable audio");
                    } else {
                        console.warn("Audio playback failed:", error.message);
                    }
                    setIsSpeaking(false);
                    conversationState.current = 'idle';
                    currentAudioPromise.current = null;
                });

        } catch (e) {
            console.error("Audio Setup Error: ", e);
            setIsSpeaking(false);
            conversationState.current = 'idle';
            currentAudioPromise.current = null;
        }
    }, []);

    const sendTextToAI = useCallback(async (userText) => {
        setIsAIResponding(true);
        if (recognition.current) {
             recognition.current.stop(); // Stop listening while AI is processing
        }

        // Access transcript via ref to make this useCallback stable
        const currentTranscript = transcriptRef.current;

        console.log('Sending to AI:', {
            userText,
            currentTranscriptLength: currentTranscript.length,
            lastFewMessages: currentTranscript.slice(-3).map(t => `${t.speaker}: ${t.text}`)
        });

        try {
            // Ensure we're sending the complete conversation history
            const history = currentTranscript.map(t => ({
                speaker: t.speaker,
                text: t.text,
                timestamp: t.timestamp
            }));

            const data = await aiRoleplay({
                userText,
                prospect,
                transcriptHistory: history,
                knowledgeMaterialIds
            });

            console.log('Received from AI:', data.text);

            // Handle fallback modes
            if (data.openai_fallback) {
                // Show subtle indicator for fallback mode
                console.log('Using OpenAI fallback responses');
            }

            // Play audio if available, otherwise just continue with text
            if (data.audio) {
                playAudio(data.audio);
            } else {
                setIsSpeaking(false);
                conversationState.current = 'idle';
            }

            setTranscript(prev => [...prev, { speaker: 'ai', text: data.text, timestamp: new Date() }]);
        } catch (error) {
            console.error("Error sending text to AI:", error);
            // Fallback response for complete failures
            const fallbackText = "I'm having some technical difficulties. Could you repeat that?";
            setTranscript(prev => [...prev, { speaker: 'ai', text: fallbackText, timestamp: new Date() }]);
            toast.error("Connection issue - please try again");
        } finally {
            setIsAIResponding(false);
        }
    }, [prospect, playAudio]); // Removed 'transcript' from dependencies due to transcriptRef

    const handleStartGreeting = useCallback(async () => {
        setCallStatus('connected');
        callStartTime.current = Date.now(); // Set call start time
        setIsAIResponding(true);
        try {
            const data = await aiRoleplay({
                userText: null,
                prospect,
                transcriptHistory: [],
                knowledgeMaterialIds
            });

            // Handle different response modes
            if (data.error || data.fallback_mode) {
                if (data.openai_fallback) {
                    toast.warning("Using simplified AI responses", {
                        description: "OpenAI service is temporarily unavailable"
                    });
                } else if (data.error && data.error.includes("ElevenLabs")) {
                    toast.info("Text-only mode active", {
                        description: "Voice features are currently unavailable"
                    });
                }
            }

            // Play audio if available, otherwise just continue with text
            if (data.audio) {
                playAudio(data.audio);
            } else {
                setIsSpeaking(false);
                conversationState.current = 'idle';
            }

            setTranscript([{ speaker: 'ai', text: data.text, timestamp: new Date() }]);
        } catch (error) {
            console.error("Error getting initial greeting:", error);
            toast.error("Could not start session. Please try again.");
            onEndCall();
        } finally {
            setIsAIResponding(false);
        }
    }, [prospect, playAudio, onEndCall]);

    // Initialize and handle the call flow
    useEffect(() => {
        // This effect runs only ONCE on mount
        handleStartGreeting();

        const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
        if (SpeechRecognition) {
            recognition.current = new SpeechRecognition();
            recognition.current.continuous = false;
            recognition.current.interimResults = false;
            recognition.current.lang = 'en-US';

            recognition.current.onstart = () => {
                setIsListening(true);
                conversationState.current = 'user_listening';
            };

            recognition.current.onresult = (event) => {
                const userText = event.results[0][0].transcript;
                setIsListening(false);
                setTranscript(prev => [...prev, { speaker: 'user', text: userText, timestamp: new Date() }]);
                sendTextToAI(userText); // sendTextToAI is now stable
            };

            recognition.current.onerror = (event) => {
                setIsListening(false);
                if (event.error !== 'no-speech' && event.error !== 'aborted') {
                    console.error("Speech recognition error:", event.error); // Log actual error for debugging
                    toast.error("Speech recognition error. Please check mic permissions.");
                }
            };

            recognition.current.onend = () => {
                setIsListening(false);
                conversationState.current = 'idle';
                // The decision to start listening again is handled by the OTHER useEffect
            };
        } else {
            toast.error("Speech recognition is not supported in this browser.");
        }

        // Capture the current audioContext value for cleanup
        const contextToClose = audioContext.current;
        // Cleanup function
        return () => {
            if (recognition.current) {
                recognition.current.abort();
                recognition.current = null; // Clear ref to avoid stale instances
            }

            // Clean up audio properly
            if (currentAudioPromise.current) {
                currentAudioPromise.current.catch(() => {}); // Ignore errors from cancelled promise
                currentAudioPromise.current = null;
            }
            if (audioPlayer.current) {
                audioPlayer.current.pause();
                audioPlayer.current.currentTime = 0;
                audioPlayer.current.onended = null; // Prevent onended from firing
                setIsSpeaking(false);
                conversationState.current = 'idle';
            }

            if (contextToClose && contextToClose.state !== 'closed') {
                contextToClose.close().catch(() => {
                    // Ignore close errors
                });
            }
        };
        // Dependencies are stable callbacks and state setters
    }, [handleStartGreeting, sendTextToAI, setIsListening, setTranscript]);

    // Effect to start listening after AI finishes speaking or on state changes
    useEffect(() => {
        if (callStatus === 'connected' && !isSpeaking && !isAIResponding && !isMuted) {
            startListening();
        }
    }, [callStatus, isSpeaking, isAIResponding, isMuted, startListening]);

    const stopAudio = () => {
        if (currentAudioPromise.current) {
            currentAudioPromise.current.catch(() => {}); // Ignore errors from cancelled promise
            currentAudioPromise.current = null;
        }
        if (audioPlayer.current) {
            audioPlayer.current.pause();
            audioPlayer.current.currentTime = 0;
            audioPlayer.current.onended = null; // Prevent onended from firing
            setIsSpeaking(false);
            conversationState.current = 'idle';
        }
    };

    const handleEndCall = async () => {
        setCallStatus('ending');

        // Stop all audio and recognition
        stopAudio();
        if (recognition.current) {
            recognition.current.stop();
        }
        if (audioContext.current && audioContext.current.state !== 'closed') {
            audioContext.current.close().catch(() => {}); // Catch and ignore errors on close
        }

        const sessionDuration = Math.floor((Date.now() - callStartTime.current) / 1000);

        let analysisData;
        let llmSucceeded = false;
        const maxRetries = 2;

        toast.info("Analyzing your performance...", { duration: 15000 });

        for (let attempt = 1; attempt <= maxRetries; attempt++) {
            try {
                const analysisPrompt = `
                Analyze this sales roleplay transcript. Provide a numerical overall score (0-100) and a brief 2-3 sentence feedback summary.

                **Conversation:**
                ${transcript.map(t => `${t.speaker === 'ai' ? prospect.name : 'Sales Rep'}: ${t.text}`).join('\n')}

                Return a valid JSON response with ONLY these two keys: "overall_score" and "feedback_summary".
                Example:
                {
                  "overall_score": 82,
                  "feedback_summary": "You did a great job building rapport and asking discovery questions. However, you could have pushed harder to secure a next step."
                }`;

                const { data } = await InvokeLLM({
                    prompt: analysisPrompt,
                    response_json_schema: {
                        type: "object",
                        properties: {
                            overall_score: { type: "number" },
                            feedback_summary: { type: "string" },
                        },
                        required: ["overall_score", "feedback_summary"]
                    }
                });

                if (data && typeof data.overall_score === 'number' && data.feedback_summary) {
                    const score = data.overall_score;
                    const scorecard = [
                        { category: "Rapport & Opening", criteria: [{ text: "Made a clear introduction", passed: score > 50 }, { text: "Established rapport effectively", passed: score > 70 }] },
                        { category: "Discovery & Listening", criteria: [{ text: "Asked relevant qualifying questions", passed: score > 60 }, { text: "Listened actively to responses", passed: score > 75 }] },
                        { category: "Value & Closing", criteria: [{ text: "Clearly articulated value", passed: score > 65 }, { text: "Attempted to set a next step", passed: score > 80 }] }
                    ];
                    analysisData = { ...data, scorecard };
                    llmSucceeded = true;
                    toast.success("Analysis complete!");
                    break; // Exit loop on success
                } else {
                    // Invalid structure, will be caught as a failure and retried
                    throw new Error(`Invalid response structure on attempt ${attempt}`);
                }
            } catch (error) {
                console.warn(`LLM analysis attempt ${attempt} failed:`, error.message);
                if (attempt === maxRetries) {
                    // Last attempt failed, proceed to fallback
                    toast.warning("AI analysis failed, using basic scoring.", {
                        description: "We'll still save your session."
                    });
                }
            }
        }
        
        if (!llmSucceeded) {
            const messageCount = transcript.length;
            const userMessages = transcript.filter(t => t.speaker === 'user').length;
            let score = 50 + Math.floor(Math.random() * 10);
            if (sessionDuration > 60) score += 15;
            if (userMessages > 3) score += 20;
            if (messageCount > 6) score += 15;

            analysisData = {
                overall_score: Math.min(score, 95), // Cap at 95 for fallback
                feedback_summary: `You completed a ${Math.round(sessionDuration/60)}-minute roleplay. ${userMessages > 3 ? 'Good engagement.' : 'Try to ask more open-ended questions.'}`,
                scorecard: [
                    { category: "Session Completion", criteria: [{ text: "Successfully completed roleplay", passed: true }, { text: "Maintained conversation flow", passed: messageCount > 4 }] }
                ]
            };
        }

        try {
            // Get current user for required fields
            const currentUser = await User.me();
            if (!currentUser || !currentUser.email) {
                throw new Error("User not found or email not available. Cannot save session.");
            }

            const sessionData = {
                session_type: "human_ai", // Required field
                lead_id: "ai_roleplay_" + Date.now(), // Generate a placeholder lead_id for AI roleplay
                initiator_email: currentUser.email, // Required field
                bot_name: prospect.name,
                bot_personality: prospect.personality,
                scenario: `${prospect.roleplay_type || 'Roleplay'} with ${prospect.name}`, // Using roleplay_type
                session_duration: sessionDuration,
                transcript: transcript.map(t => ({
                    speaker: t.speaker,
                    text: t.text,
                    timestamp: t.timestamp.toISOString()
                })),
                analysis_results: analysisData,
                call_type: (prospect.roleplay_type || 'roleplay').toLowerCase().replace(' ', '_'), // Using roleplay_type
                tags: [prospect.personality, prospect.roleplay_type].filter(Boolean), // Using roleplay_type
                // Store complete bot configuration for "Practice Again" functionality
                bot_configuration: JSON.stringify({
                    name: prospect.name,
                    title: prospect.title,
                    company_name: prospect.company_name || prospect.company,
                    personality: prospect.personality,
                    roleplay_type: prospect.roleplay_type,
                    voice: prospect.voice || 'english_male',
                    language: prospect.language || 'english',
                    traits: prospect.traits || [],
                    painPoints: prospect.painPoints || [],
                    background: prospect.background || '',
                    difficulty: prospect.difficulty || 'Medium',
                    industry: prospect.industry,
                    // Include any other relevant bot properties
                    isLeadSpecific: prospect.isLeadSpecific,
                    isLibraryPractice: prospect.isLibraryPractice,
                    referenceSubmissionId: prospect.referenceSubmissionId
                }),
                // Additional fields for AI roleplay context
                feedback: {
                    ai_analysis: JSON.stringify(analysisData)
                },
                evaluation_scores: {
                    overall_score: analysisData.overall_score,
                    communication_clarity: Math.max(0, Math.min(100, analysisData.overall_score + Math.floor(Math.random() * 10) - 5)),
                    product_knowledge: Math.max(0, Math.min(100, analysisData.overall_score + Math.floor(Math.random() * 10) - 5)),
                    objection_handling: Math.max(0, Math.min(100, analysisData.overall_score + Math.floor(Math.random() * 10) - 5)),
                    closing_technique: Math.max(0, Math.min(100, analysisData.overall_score + Math.floor(Math.random() * 10) - 5))
                }
            };

            console.log('Attempting to save session data:', JSON.stringify(sessionData, null, 2));
            const savedSession = await RoleplaySession.create(sessionData);

            if (!savedSession || !savedSession.id) {
                throw new Error("Session creation in database did not return a valid ID.");
            }

            console.log('Session created successfully in database with ID:', savedSession.id);

            onAnalysisComplete(savedSession);

        } catch (saveError) {
            console.error('Fatal error saving roleplay session:', saveError);
            toast.error("Could not save your session. Please copy the transcript if needed.", { duration: 10000 });
            onEndCall();
        }
    };

    const toggleMute = () => {
        setIsMuted(prev => {
            const newMutedState = !prev;
            if (newMutedState) {
                if (recognition.current) recognition.current.stop();
                toast.info("Microphone muted");
            } else {
                toast.success("Microphone on");
                startListening();
            }
            return newMutedState;
        });
    };

    const toggleAudioMute = () => {
        setIsAudioMuted(prev => {
            const next = !prev;
            if (audioPlayer.current) {
                audioPlayer.current.muted = next;
            }
            toast.info(next ? "AI audio muted" : "AI audio on");
            return next;
        });
    };

    return (
        <div className="fixed inset-0 bg-black bg-opacity-80 flex items-center justify-center z-50 p-4">
            <div className="w-full max-w-7xl h-[90vh] bg-white rounded-lg shadow-2xl flex overflow-hidden transition-all duration-300">
                {/* Assistant Sidebar */}
                <div className={`transition-all duration-300 ease-in-out ${isSidebarOpen ? 'w-96' : 'w-0'} overflow-hidden`}>
                    <CallAssistantSidebar prospect={prospect} />
                </div>

                {/* Main Call View */}
                <div className="flex-1 flex flex-col">
                    <Card className="w-full h-full flex flex-col bg-white shadow-none rounded-none border-0">
                        <CardHeader className="flex-shrink-0 bg-slate-100/80 backdrop-blur-sm border-b">
                            <div className="flex items-center justify-between">
                                <div className="flex items-center gap-4">
                                     <Button variant="ghost" size="icon" onClick={() => setIsSidebarOpen(!isSidebarOpen)} className="text-slate-500 hover:text-slate-900">
                                        {isSidebarOpen ? <ChevronLeft className="w-5 h-5" /> : <ChevronRight className="w-5 h-5" />}
                                    </Button>
                                    <div className="w-12 h-12 bg-gradient-to-br from-blue-500 to-purple-500 rounded-full flex items-center justify-center text-white font-bold">
                                        {prospect.name?.split(' ').map(n => n[0]).join('') || 'B'}
                                    </div>
                                    <div>
                                        <CardTitle className="text-xl">
                                            On call with {prospect.name}
                                        </CardTitle>
                                        <CardDescription>{prospect.title} at {prospect.company_name || prospect.company}</CardDescription>
                                    </div>

                                </div>
                                <div className="flex items-center gap-2 text-green-600">
                                    <Phone className="w-5 h-5 animate-pulse" />
                                    <span className="text-sm">Connected</span>
                                </div>
                            </div>
                        </CardHeader>

                        <CardContent className="flex-1 overflow-y-auto p-4 space-y-4">
                            {transcript.map((item, index) => (
                                <div key={index} className={`flex items-start gap-3 ${item.speaker === 'user' ? 'justify-end' : ''}`}>
                                    {item.speaker === 'ai' && (
                                        <Avatar className="w-10 h-10">
                                            <AvatarFallback className="bg-slate-200">
                                                {prospect.name?.charAt(0) || 'B'}
                                            </AvatarFallback>
                                        </Avatar>
                                    )}
                                    <div className={`max-w-[70%] p-3 rounded-lg ${
                                        item.speaker === 'user' ? 'bg-blue-500 text-white' : 'bg-slate-100'
                                    }`}>
                                        <p className="font-medium text-sm capitalize">
                                            {item.speaker === 'user' ? 'You' : prospect.name}
                                        </p>
                                        <p>{item.text}</p>
                                    </div>
                                    {item.speaker === 'user' && (
                                        <Avatar className="w-10 h-10">
                                            <AvatarFallback className="bg-blue-500 text-white">Y</AvatarFallback>
                                        </Avatar>
                                    )}
                                </div>
                            ))}
                            {isAIResponding && !isSpeaking && (
                                <div className="flex justify-start items-center gap-2 text-slate-500">
                                    <Loader2 className="w-4 h-4 animate-spin" />
                                    <span>{prospect.name} is thinking...</span>
                                </div>
                            )}
                            {isListening && !isMuted && (
                                 <div className="flex justify-center items-center gap-2 text-blue-600">
                                     <Mic className="w-4 h-4 animate-pulse" />
                                    <span>Listening...</span>
                                </div>
                            )}
                            <div ref={messagesEndRef} />
                        </CardContent>

                        <CardFooter className="flex-shrink-0 border-t p-4 bg-slate-50/50">
                            <div className="flex items-center justify-between w-full">
                                <div className="flex items-center gap-4">
                                    <Button
                                        onClick={toggleMute}
                                        variant="outline"
                                        size="icon"
                                        className={`w-14 h-14 rounded-full ${isMuted ? 'bg-red-500 text-white hover:bg-red-600' : ''}`}
                                    >
                                        {isMuted ? <MicOff className="w-6 h-6" /> : <Mic className="w-6 h-6" />}
                                    </Button>
                                    <Button
                                        variant="outline"
                                        size="icon"
                                        onClick={toggleAudioMute}
                                        className={`w-14 h-14 rounded-full ${isAudioMuted ? 'bg-orange-500 text-white hover:bg-orange-600' : ''}`}
                                        title={isAudioMuted ? "Unmute AI audio" : "Mute AI audio"}
                                    >
                                        {isAudioMuted ? <VolumeX className="w-6 h-6" /> : <Volume2 className="w-6 h-6" />}
                                    </Button>
                                </div>
                                <Button onClick={handleEndCall} variant="destructive" size="lg">
                                    <Phone className="w-5 h-5 mr-2" />
                                    End Call & Analyze
                                </Button>
                            </div>
                        </CardFooter>
                    </Card>
                </div>
            </div>
        </div>
    );
};

const ProspectCard = ({ prospect, onStartCall, onDelete, isSelected, onCardClick }) => {
    const [isDeleting, setIsDeleting] = useState(false);
    const navigate = useNavigate(); // <-- Add useNavigate hook

    const handleDelete = async (e) => {
        e.stopPropagation();
        if (!confirm(`Are you sure you want to delete ${prospect.name}?`)) {
            return;
        }

        setIsDeleting(true);
        try {
            await RoleplayBot.delete(prospect.id);
            toast.success(`${prospect.name} has been deleted`);
            onDelete(prospect.id);
        } catch (error) {
            console.error("Failed to delete bot:", error);
            toast.error("Failed to delete bot");
        } finally {
            setIsDeleting(false);
        }
    };

    const handleCardClick = (e) => {
        // Don't trigger card selection if clicking delete button or start call button
        if (e.target.closest('button')) return;
        onCardClick(prospect);
    };

    const handleViewDetails = (e) => {
        e.stopPropagation();
        // Use navigate for SPA-friendly navigation
        navigate(createPageUrl(`BotOverview?bot_name=${encodeURIComponent(prospect.name)}`));
    };

    return (
        <Card
            className={`group transition-all duration-200 hover:shadow-lg bg-white relative cursor-pointer border-l-4 border-l-blue-500 ${
                isSelected ? 'ring-2 ring-blue-500' : 'hover:ring-2 hover:ring-blue-500'
            }`}
            onClick={handleCardClick}
        >
            {/* Delete Button */}
            <Button
                variant="ghost"
                size="icon"
                className="absolute top-2 right-2 w-8 h-8 text-gray-400 hover:text-red-500 z-10"
                onClick={handleDelete}
                disabled={isDeleting}
            >
                {isDeleting ? (
                    <Loader2 className="w-4 h-4 animate-spin" />
                ) : (
                    <X className="w-4 h-4" />
                )}
            </Button>

            <CardHeader className="pb-3 flex items-start justify-between">
                <div className="flex items-center gap-3">
                    <div className="relative">
                        <div className="w-12 h-12 bg-gradient-to-br from-blue-500 to-purple-500 rounded-full flex items-center justify-center text-white font-bold text-lg">
                            {prospect.name?.split(' ').map(n => n[0]).join('') || 'B'}
                        </div>
                        <Badge className="absolute -top-1 -right-1 bg-blue-100 text-blue-800 text-xs px-1">
                            <Sparkles className="w-3 h-3 mr-1" />
                            AI
                        </Badge>
                    </div>
                    <div>
                        <CardTitle className="text-lg font-bold text-slate-900 group-hover:text-blue-600 transition-colors">
                            {prospect.name}
                        </CardTitle>
                        <p className="text-sm text-slate-600">{prospect.title} at {prospect.company_name}</p>
                        {prospect.industry && (
                            <Badge className="mt-1 text-xs" variant="outline">
                                {prospect.industry}
                            </Badge>
                        )}
                    </div>
                </div>
            </CardHeader>

            <CardContent className="p-6 pt-0 text-left">
                <div className="flex gap-2 mb-4 flex-wrap">
                    <Badge variant="outline" className="text-xs">{prospect.personality}</Badge>
                    {prospect.roleplay_type && (
                        <Badge className="text-xs bg-purple-100 text-purple-800">
                            {prospect.roleplay_type}
                        </Badge>
                    )}
                    <Badge variant="outline" className="text-xs">{prospect.language || 'English'}</Badge>
                </div>

                <div className="space-y-2">
                    <Button
                        variant="outline"
                        size="sm"
                        onClick={handleViewDetails}
                        className="w-full border-blue-200 text-blue-600 hover:bg-blue-50"
                    >
                        <Eye className="w-4 h-4 mr-2" />
                        View Details
                    </Button>
                    <Button
                        className="w-full bg-blue-500 hover:bg-blue-600 text-white"
                        onClick={() => onStartCall(prospect)}
                    >
                        <Phone className="w-4 h-4 mr-2"/>
                        Start Voice Roleplay
                    </Button>
                </div>
            </CardContent>
        </Card>
    );
};

export default function AIRoleplay() {
    const [allBots, setAllBots] = useState([]);
    const [filteredBots, setFilteredBots] = useState([]);
    const [searchTerm, setSearchTerm] = useState('');
    const [selectedIndustry, setSelectedIndustry] = useState('all');
    const [selectedCallType, setSelectedCallType] = useState('all');
    const [selectedBot, setSelectedBot] = useState(null);
    const [showCallModal, setShowCallModal] = useState(false);
    const [showConfirmationModal, setShowConfirmationModal] = useState(false);
    const [botToCall, setBotToCall] = useState(null);
    const [selectedProspectId, setSelectedProspectId] = useState(null);
    const location = useLocation();
    const navigate = useNavigate();

    const [knowledgeMaterials, setKnowledgeMaterials] = useState([]);
    const [selectedMaterials, setSelectedMaterials] = useState([]);

    const [showUploadModal, setShowUploadModal] = useState(false);
    const [uploadTab, setUploadTab] = useState('file');
    const [isDragging, setIsDragging] = useState(false);
    const [isUploading, setIsUploading] = useState(false);
    const [currentUser, setCurrentUser] = useState(null);
    const [newMaterial, setNewMaterial] = useState({
        title: '', description: '', material_type: 'document',
        file_url: '', content_text: '', category: 'General Training'
    });
    const fileInputRef = useRef(null);

    // Enhanced lead-specific roleplay state
    const [isLeadSpecific, setIsLeadSpecific] = useState(false);
    const [leadRoleplayBot, setLeadRoleplayBot] = useState(null);

    // New states and hooks for AI Coach embedding (not used in this change, but kept)
    const [isLoading, setIsLoading] = useState(false);
    const [isRecording, setIsRecording] = useState(false);
    const [audioUrl, setAudioUrl] = useState(null);
    const [transcript, setTranscript] = useState([]); // This transcript is for this component, not the one in CallInProgress
    const [isResponding, setIsResponding] = useState(false);
    const [mediaRecorder, setMediaRecorder] = useState(null);
    const [audioContext, setAudioContext] = useState(null); // This audioContext is for this component, not the one in CallInProgress
    const [analyser, setAnalyser] = useState(null);
    const [dataArray, setDataArray] = useState(null);
    const visualizerRef = useRef(null);
    const animationFrameId = useRef(null);

    // Industry options for filtering
    const industries = ['all', 'Healthcare', 'Legal', 'HR', 'Finance', 'Technology', 'Manufacturing'];

    useEffect(() => {
        const fetchBots = async () => {
            try {
                const bots = await RoleplayBot.list();
                // Add a 'name' field by combining first and last names
                const botsWithName = bots.map(bot => ({
                    ...bot,
                    name: [bot.first_name, bot.last_name].filter(Boolean).join(' ') || 'Unknown Bot'
                }));
                setAllBots(botsWithName);
                setFilteredBots(botsWithName); // INITIALIZE filteredBots
                console.log('Fetched bots:', botsWithName); // Debug log
            } catch (error) {
                console.error("Failed to fetch roleplay bots:", error);
                toast.error("Failed to load roleplay bots.");
                setAllBots([]); // Ensure we show empty state instead of cached data
                setFilteredBots([]); // Ensure we show empty state instead of cached data
            }
        };

        const fetchKnowledgeMaterials = async () => {
            try {
                const { data, error } = await supabase
                    .from('roleplay_knowledge_materials')
                    .select('*')
                    .eq('is_active', true)
                    .order('created_date', { ascending: false });

                if (error) throw error;
                setKnowledgeMaterials(data || []);
            } catch (error) {
                console.error("Failed to fetch knowledge materials:", error);
            }
        };

        const fetchCurrentUser = async () => {
            try {
                const user = await User.me();
                setCurrentUser(user);
            } catch (e) {}
        };

        fetchBots();
        fetchKnowledgeMaterials();
        fetchCurrentUser();
    }, []);

    useEffect(() => {
        const searchParams = new URLSearchParams(location.search);
        const botId = searchParams.get('botId');

        if (botId) {
            const loadBotFromId = async () => {
                try {
                    let botData = null;

                    if (!botId.startsWith('dummy_')) {
                        const { data, error } = await supabase
                            .from('ai_clients')
                            .select('*')
                            .eq('id', botId)
                            .maybeSingle();

                        if (error && error.code !== 'PGRST116') throw error;

                        if (data) {
                            const fullName = `${data.first_name || ''} ${data.last_name || ''}`.trim() || 'Practice Partner';
                            botData = {
                                ...data,
                                name: fullName,
                                first_name: data.first_name || fullName.split(' ')[0],
                                last_name: data.last_name || fullName.split(' ').slice(1).join(' ') || '',
                                title: data.title || 'Professional',
                                company: data.company_name || data.company || 'Company',
                                company_name: data.company_name || data.company || 'Company',
                                personas: data.personas_config || [{}],
                                isLibraryPractice: true
                            };
                        }
                    }

                    if (!botData && botId.startsWith('dummy_')) {
                        const DUMMY_BOTS = [
                            { id: 'dummy_cold_call_tech',        persona: { name: 'Sarah Johnson',    title: 'CTO',                gender: 'Female', personality: 'Skeptical',    nationality: 'US' }, company: 'TechCorp Inc',           roleplay_type: 'Cold Call' },
                            { id: 'dummy_discovery_finance',     persona: { name: 'Michael Chen',     title: 'Finance Director',   gender: 'Male',   personality: 'Analytical',   nationality: 'US' }, company: 'GlobalFinance Solutions', roleplay_type: 'Discovery Call' },
                            { id: 'dummy_warm_call_ecommerce',   persona: { name: 'Rachel Martinez',  title: 'E-commerce Manager', gender: 'Female', personality: 'Friendly',     nationality: 'US' }, company: 'ShopHub Co',              roleplay_type: 'Warm Call' },
                            { id: 'dummy_objection_healthcare',  persona: { name: 'Dr. James Wilson', title: 'IT Director',        gender: 'Male',   personality: 'Aggressive',   nationality: 'US' }, company: 'MediTech Solutions',      roleplay_type: 'Objection Handling' },
                            { id: 'dummy_renewal_call_mfg',      persona: { name: 'David Kumar',      title: 'VP Operations',      gender: 'Male',   personality: 'Reserved',     nationality: 'Indian' }, company: 'Industrial Solutions Inc', roleplay_type: 'Renewal Call' },
                            { id: 'dummy_negotiation_enterprise', persona: { name: 'Patricia Adams',  title: 'VP Procurement',     gender: 'Female', personality: 'Aggressive',   nationality: 'US' }, company: 'Fortune500 Corp',         roleplay_type: 'Negotiation' },
                            { id: 'dummy_multistakeholder_deal', persona: { name: 'Lisa Thompson',    title: 'Head of IT',         gender: 'Female', personality: 'Analytical',   nationality: 'UK' }, company: 'BigTech Solutions',       roleplay_type: 'Discovery Call' },
                            { id: 'dummy_executive_brief',       persona: { name: 'Richard Blackwell',title: 'CEO',                gender: 'Male',   personality: 'Authoritative',nationality: 'UK' }, company: 'McKinsey Advisory',       roleplay_type: 'Cold Call' },
                            { id: 'dummy_value_based_selling',   persona: { name: 'Angela Foster',    title: 'Operations Director',gender: 'Female', personality: 'Cooperative',  nationality: 'US' }, company: 'Accenture Services',      roleplay_type: 'Discovery Call' },
                            { id: 'dummy_complex_sale',          persona: { name: 'Jennifer Park',    title: 'Chief Risk Officer', gender: 'Female', personality: 'Skeptical',    nationality: 'US' }, company: 'Goldman Sachs',           roleplay_type: 'Negotiation' },
                        ];

                        const dummyBot = DUMMY_BOTS.find(b => b.id === botId);
                        if (dummyBot) {
                            const p = dummyBot.persona;
                            botData = {
                                id: dummyBot.id,
                                name: p.name,
                                first_name: p.name.split(' ')[0],
                                last_name: p.name.split(' ').slice(1).join(' '),
                                title: p.title,
                                company: dummyBot.company,
                                company_name: dummyBot.company,
                                gender: p.gender,
                                personality: p.personality,
                                nationality: p.nationality,
                                roleplay_type: dummyBot.roleplay_type,
                                personas_config: [p],
                                personas: [p],
                                isLibraryPractice: true
                            };
                        }
                    }

                    if (botData) {
                        setBotToCall(botData);
                        setShowConfirmationModal(true);
                    } else {
                        toast.error('Practice scenario not found');
                    }
                } catch (error) {
                    console.error('Error loading bot:', error);
                    toast.error('Failed to load practice scenario');
                }
            };

            loadBotFromId();
        }
    }, [location.search]);

    const handleStartCall = useCallback((bot) => {
        setBotToCall(bot);
        setShowConfirmationModal(true);
    }, []);

    // Helper functions to infer context based on job title (MOVED HERE)
    const getTraitsForTitle = useCallback((title) => {
        const lowerTitle = title.toLowerCase();
        if (lowerTitle.includes('ceo') || lowerTitle.includes('founder')) {
            return ['Strategic', 'Time-conscious', 'Results-focused'];
        } else if (lowerTitle.includes('cto') || lowerTitle.includes('technical')) {
            return ['Technical', 'Detail-oriented', 'Security-focused'];
        } else if (lowerTitle.includes('cfo') || lowerTitle.includes('finance')) {
            return ['ROI-focused', 'Cost-conscious', 'Data-driven'];
        } else if (lowerTitle.includes('operations') || lowerTitle.includes('ops')) {
            return ['Process-focused', 'Efficiency-minded', 'Practical'];
        } else if (lowerTitle.includes('marketing')) {
            return ['Brand-focused', 'Growth-oriented', 'Creative'];
        } else if (lowerTitle.includes('sales')) {
            return ['Revenue-focused', 'Relationship-oriented', 'Goal-driven'];
        }
        return ['Professional', 'Busy', 'Results-oriented'];
    }, []); // No external dependencies, so an empty array is fine

    const getPainPointsForTitle = useCallback((title) => {
        const lowerTitle = title.toLowerCase();
        if (lowerTitle.includes('ceo') || lowerTitle.includes('founder')) {
            return ['Market competition', 'Scaling challenges', 'Investor pressure'];
        } else if (lowerTitle.includes('cto') || lowerTitle.includes('technical')) {
            return ['Technical debt', 'Security concerns', 'System scalability'];
        } else if (lowerTitle.includes('cfo') || lowerTitle.includes('finance')) {
            return ['Budget constraints', 'Cost optimization', 'Financial reporting'];
        } else if (lowerTitle.includes('operations') || lowerTitle.includes('ops')) {
            return ['Process inefficiencies', 'Resource allocation', 'Quality control'];
        } else if (lowerTitle.includes('marketing')) {
            return ['Lead generation', 'Brand awareness', 'Campaign ROI'];
        } else if (lowerTitle.includes('sales')) {
            return ['Sales targets', 'Pipeline management', 'Customer acquisition'];
        }
        return ['Operational challenges', 'Budget pressures', 'Time constraints'];
    }, []); // No external dependencies, so an empty array is fine

    const getBusinessFocusForTitle = useCallback((title) => {
        const lowerTitle = title.toLowerCase();
        if (lowerTitle.includes('ceo') || lowerTitle.includes('founder')) {
            return 'overall business growth and strategic initiatives';
        } else if (lowerTitle.includes('cto') || lowerTitle.includes('technical')) {
            return 'technology infrastructure and innovation';
        } else if (lowerTitle.includes('cfo') || lowerTitle.includes('finance')) {
            return 'financial performance and cost management';
        } else if (lowerTitle.includes('operations') || lowerTitle.includes('ops')) {
            return 'operational efficiency and process optimization';
        }
        return 'their department goals and business objectives';
    }, []); // No external dependencies, so an empty array is fine

    // Effect to handle direct practice flow and "Practice Again" flow from URL
    useEffect(() => {
        const params = new URLSearchParams(location.search);
        const autoStart = params.get('auto_start');
        const botDataParam = params.get('bot_data');

        // Handle direct auto-start (from Practice Again button)
        if (autoStart === 'true' && botDataParam) {
            try {
                const botData = JSON.parse(decodeURIComponent(botDataParam));
                handleStartCall(botData);
                // Clean up URL
                navigate(location.pathname, { replace: true });
                return;
            } catch (error) {
                console.error('Error parsing bot data:', error);
            }
        }

        // Handle lead-specific and library practice from URL parameters
        const name = params.get('name');
        const title = params.get('title');
        const company = params.get('company'); // Original param
        const personality = params.get('personality') || 'Nice';
        const scenario = params.get('scenario');
        const scenarioTitle = params.get('scenarioTitle');
        const referenceSubmissionId = params.get('referenceSubmissionId');

        if (name && title && company) {
            // Lead-specific roleplay (existing logic)
            const customBot = {
                name: name,
                title: title,
                company_name: company, // Use company_name for consistency
                personality: personality,
                voice: 'english_male',
                language: 'english',
                traits: getTraitsForTitle(title),
                painPoints: getPainPointsForTitle(title),
                background: `${name} is a ${title} at ${company}. They are likely focused on ${getBusinessFocusForTitle(title)}.`,
                difficulty: 'Medium',
                roleplay_type: 'Cold Call', // Changed from callType to roleplay_type
                isLeadSpecific: true
            };

            setIsLeadSpecific(true);
            setLeadRoleplayBot(customBot);

            // Show confirmation modal for lead-specific practice
            setBotToCall(customBot);
            setShowConfirmationModal(true);

            toast.success(`Pitch practice configured for ${name}!`, {
                description: `You'll be practicing with an AI version of ${name} from ${company}`
            });
        } else if (scenario && scenarioTitle) {
            // Pitch Library scenario roleplay
            const customBot = {
                name: 'Practice Prospect',
                title: scenarioTitle || 'Decision Maker', // Use scenarioTitle for the bot's title
                company_name: 'Target Company', // Use company_name for consistency
                personality: personality, // Could be fixed or derived if needed
                voice: 'english_male',
                language: 'english',
                traits: ['Professional', 'Analytical', 'Time-conscious'],
                painPoints: ['Budget constraints', 'Implementation concerns', 'ROI questions'],
                background: scenario, // The scenario description as the bot's background
                difficulty: 'Medium',
                roleplay_type: 'Practice Call', // Changed from callType to roleplay_type
                isLibraryPractice: true,
                referenceSubmissionId: referenceSubmissionId
            };

            setIsLeadSpecific(true); // Treat library practice as a specific scenario type
            setLeadRoleplayBot(customBot);
            setBotToCall(customBot);
            setShowConfirmationModal(true);

            toast.success('Practice session ready!', {
                description: 'You\'ll be practicing this scenario from the Pitch Library'
            });
        }
    }, [location.search, navigate, handleStartCall, location.pathname, getTraitsForTitle, getPainPointsForTitle, getBusinessFocusForTitle]);

    // Effect for filtering bots based on search term, industry, and call type
    useEffect(() => {
        let currentFiltered = allBots;

        if (searchTerm) {
            currentFiltered = currentFiltered.filter(bot =>
                bot.name?.toLowerCase().includes(searchTerm.toLowerCase()) ||
                bot.company_name?.toLowerCase().includes(searchTerm.toLowerCase()) ||
                bot.title?.toLowerCase().includes(searchTerm.toLowerCase())
            );
        }

        if (selectedIndustry !== 'all') {
            currentFiltered = currentFiltered.filter(bot => bot.industry?.toLowerCase() === selectedIndustry.toLowerCase());
        }

        if (selectedCallType !== 'all') {
            currentFiltered = currentFiltered.filter(bot => bot.roleplay_type?.toLowerCase() === selectedCallType.toLowerCase());
        }

        setFilteredBots(currentFiltered);
    }, [allBots, searchTerm, selectedIndustry, selectedCallType]);


    const handleDeleteBot = (deletedBotId) => {
        setAllBots(prevBots => prevBots.filter(bot => bot.id !== deletedBotId));
    };

    // Determine the correct back navigation
    const getBackUrl = () => {
        const returnToPitchLibrary = sessionStorage.getItem('returnToPitchLibrary');
        if (returnToPitchLibrary === 'true') {
            return createPageUrl('PitchLibrary');
        }
        const returnToCallPrep = sessionStorage.getItem('returnToCallPrep');
        if (returnToCallPrep === 'true') {
            return createPageUrl('CallPrep');
        }
        return createPageUrl('Dashboard');
    };

    const getBackLabel = () => {
        const returnToPitchLibrary = sessionStorage.getItem('returnToPitchLibrary');
        if (returnToPitchLibrary === 'true') {
            return 'Back to Pitch Library';
        }
        const returnToCallPrep = sessionStorage.getItem('returnToCallPrep');
        if (returnToCallPrep === 'true') {
            return 'Back to Call Prep';
        }
        return 'Back to Dashboard';
    };

    // Clear the return flag when leaving the page
    useEffect(() => {
        return () => {
            sessionStorage.removeItem('returnToPitchLibrary');
            sessionStorage.removeItem('returnToCallPrep');
        };
    }, []);

    const confirmStartCall = () => {
        setShowConfirmationModal(false);
        if (botToCall) {
            const voiceId = resolveElevenLabsVoiceId(botToCall);
            setSelectedBot({ ...botToCall, voiceId });
            setShowCallModal(true);
        }
    };

    const toggleMaterial = (materialId) => {
        setSelectedMaterials(prev =>
            prev.includes(materialId)
                ? prev.filter(id => id !== materialId)
                : [...prev, materialId]
        );
    };

    const handleFileUpload = async (file) => {
        if (!file) return;
        if (file.size > 50 * 1024 * 1024) { toast.error('File size exceeds 50MB limit'); return; }
        setIsUploading(true);
        try {
            const fileExt = file.name.split('.').pop().toLowerCase();
            const fileName = `${Date.now()}-${Math.random().toString(36).substring(7)}.${fileExt}`;
            const filePath = `knowledge-materials/${currentUser?.company_id || 'public'}/${fileName}`;
            const { error: uploadError } = await supabase.storage.from('documents').upload(filePath, file, { cacheControl: '3600', upsert: false });
            if (uploadError) throw new Error(uploadError.message || 'Upload failed');
            const { data: { publicUrl } } = supabase.storage.from('documents').getPublicUrl(filePath);
            const titleGuess = file.name.replace(/\.[^/.]+$/, '').replace(/[-_]/g, ' ');
            setNewMaterial(prev => ({
                ...prev, file_url: publicUrl, title: prev.title || titleGuess,
                material_type: ['mp4', 'mov', 'avi'].includes(fileExt) ? 'video' : ['mp3', 'wav', 'm4a'].includes(fileExt) ? 'audio' : 'document'
            }));
            toast.success('File uploaded — add a title and save');
        } catch (error) { toast.error(error.message || 'Failed to upload file'); }
        finally { setIsUploading(false); }
    };

    const handleSaveMaterial = async () => {
        if (!newMaterial.title.trim()) { toast.error('Please enter a title'); return; }
        if (newMaterial.material_type === 'text' && !newMaterial.content_text.trim()) { toast.error('Please enter the text content'); return; }
        if (newMaterial.material_type !== 'text' && !newMaterial.file_url.trim()) { toast.error('Please upload a file or enter a URL'); return; }
        try {
            const { data, error } = await supabase.from('roleplay_knowledge_materials').insert({
                ...newMaterial, uploaded_by: currentUser?.email || '', company_id: currentUser?.company_id, is_active: true
            }).select().single();
            if (error) throw error;
            setKnowledgeMaterials(prev => [data, ...prev]);
            setSelectedMaterials(prev => [...prev, data.id]);
            setNewMaterial({ title: '', description: '', material_type: 'document', file_url: '', content_text: '', category: 'General Training' });
            setUploadTab('file');
            setShowUploadModal(false);
            toast.success('Material added and selected');
        } catch (error) { toast.error('Failed to save material'); }
    };

    const handleAnalysisComplete = (session) => {
        setShowCallModal(false); // Close the call modal when analysis is complete
        setSelectedBot(null); // Clear selected bot
        if (session && session.id) {
            toast.success("Call analysis complete!");
            // Navigate to dedicated analysis page with unique URL using navigate
            navigate(createPageUrl(`AIRoleplayAnalysis?id=${session.id}`));
        } else {
            toast.error("Could not retrieve analysis results.");
        }
    };

    const handleImmediateCallEnd = () => {
        setShowCallModal(false);
    };

    const handleStartRecording = async () => {
        // Placeholder for the recording logic.
        // The actual implementation would involve MediaRecorder API,
        // setting up audio streams, and handling audio data.
        console.log("Starting recording... (function not fully implemented in outline)");
        setIsRecording(true);
        // Example: attempt to get media stream
        try {
            const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
            // Here you would initialize MediaRecorder with the stream,
            // set up event listeners for 'dataavailable' and 'stop',
            // and start recording.
        } catch (error) {
            console.error("Error accessing microphone:", error);
            toast.error("Failed to access microphone. Please check mic permissions.");
            setIsRecording(false);
        }
    };

    return (
        <div className="p-6 md:p-10 bg-slate-100 min-h-screen">
            {/* Add back button */}
            <div className="mb-6">
                <Link to={getBackUrl()} className="inline-flex items-center gap-2 text-sm text-slate-600 hover:text-slate-900 transition-colors">
                    <ArrowLeft className="w-4 h-4" />
                    {getBackLabel()}
                </Link>
            </div>

            <div className="flex justify-between items-center mb-8">
                <div>
                    <h1 className="text-4xl font-bold text-slate-900 mb-2">
                        {isLeadSpecific ? `Pitch Practice with ${leadRoleplayBot?.name}` : 'AI Sales Roleplay'}
                    </h1>
                    <p className="text-slate-600 max-w-3xl">
                        {isLeadSpecific
                            ? `Practice your pitch with an AI version of ${leadRoleplayBot?.name} from ${leadRoleplayBot?.company_name}`
                            : 'Practice with AI prospects to sharpen your sales skills in real-time. Create a new bot or choose from the list below.'
                        }
                    </p>
                </div>
                 {!isLeadSpecific && (
                    <div className="flex gap-3">
                        <Link to={createPageUrl('MultiPartyRoleplay')}>
                            <Button size="lg" variant="outline" className="bg-purple-50 border-purple-200 text-purple-700 hover:bg-purple-100">
                                <Users className="w-5 h-5 mr-2" />
                                Multi-Party Roleplay
                            </Button>
                        </Link>
                        <Button asChild size="lg" className="bg-blue-600 hover:bg-blue-700">
                            <Link to={createPageUrl('CreateRoleplayBot')}>
                                <Plus className="w-5 h-5 mr-2" />
                                Create New Bot
                            </Link>
                        </Button>
                    </div>
                )}
            </div>

            {isLeadSpecific && leadRoleplayBot && (
                <div className="max-w-4xl mx-auto mb-8">
                    <div className="bg-gradient-to-r from-purple-100 to-blue-100 rounded-xl p-6 border border-purple-200">
                        <div className="flex items-center gap-4 mb-4">
                            <div className="w-16 h-16 bg-gradient-to-br from-purple-500 to-blue-500 rounded-full flex items-center justify-center text-white font-bold text-xl">
                                {leadRoleplayBot.name?.charAt(0) || 'B'}
                            </div>
                            <div>
                                <h3 className="text-xl font-bold text-slate-900">{leadRoleplayBot.name}</h3>
                                <p className="text-slate-600">{leadRoleplayBot.title} at {leadRoleplayBot.company_name}</p>
                            </div>
                        </div>

                        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-sm">
                            <div>
                                <p className="font-medium text-slate-700 mb-2">Personality Traits</p>
                                <div className="flex flex-wrap gap-1">
                                    {leadRoleplayBot.traits?.map((trait, index) => (
                                        <span key={index} className="px-2 py-1 bg-purple-100 text-purple-700 rounded-full text-xs">{trait}</span>
                                    ))}
                                </div>
                            </div>
                            <div>
                                <p className="font-medium text-slate-700 mb-2">Likely Pain Points</p>
                                <div className="flex flex-wrap gap-1">
                                    {leadRoleplayBot.painPoints?.map((pain, index) => (
                                        <span key={index} className="px-2 py-1 bg-red-100 text-red-700 rounded-full text-xs">{pain}</span>
                                    ))}
                                </div>
                            </div>
                            <div>
                                <p className="font-medium text-slate-700 mb-2">Background</p>
                                <p className="text-slate-600 text-xs">{leadRoleplayBot.background}</p>
                            </div>
                        </div>
                    </div>
                </div>
            )}

            {!isLeadSpecific && (
                <>
                    <AIRoleplayInsights prospects={allBots} onSelectProspect={handleStartCall} />

                    <div className="flex flex-col sm:flex-row gap-4 mb-8">
                        <div className="relative flex-1">
                            <Search className="absolute left-3 top-3 h-4 w-4 text-slate-400" />
                            <Input
                                placeholder="Search bots by name, title, or company..."
                                value={searchTerm}
                                onChange={(e) => setSearchTerm(e.target.value)}
                                className="pl-10"
                            />
                        </div>
                        <Select value={selectedIndustry} onValueChange={setSelectedIndustry}>
                            <SelectTrigger className="w-full sm:w-48">
                                <SelectValue placeholder="Filter by Industry" />
                            </SelectTrigger>
                            <SelectContent>
                                {industries.map(industry => (
                                    <SelectItem key={industry} value={industry}>
                                        {industry === 'all' ? 'All Industries' : industry}
                                    </SelectItem>
                                ))}
                            </SelectContent>
                        </Select>
                        <Select value={selectedCallType} onValueChange={setSelectedCallType}>
                            <SelectTrigger className="w-full sm:w-48">
                                <SelectValue placeholder="Filter by Call Type" />
                            </SelectTrigger>
                            <SelectContent>
                                <SelectItem value="all">All Call Types</SelectItem>
                                <SelectItem value="Cold Call">Cold Call</SelectItem>
                                <SelectItem value="Discovery Call">Discovery Call</SelectItem>
                                <SelectItem value="Demo">Demo</SelectItem>
                                <SelectItem value="Follow-up">Follow-up</SelectItem>
                            </SelectContent>
                        </Select>
                    </div>

                    <div className="flex items-center gap-2 mb-6">
                        <Users className="w-5 h-5 text-slate-600" />
                        <span className="text-lg font-semibold text-slate-800">Available Bots</span>
                        <span className="text-slate-500">({filteredBots.length} found)</span>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                        {filteredBots.map((prospectItem) => (
                            <ProspectCard
                                key={prospectItem.id}
                                prospect={prospectItem}
                                onStartCall={handleStartCall}
                                onDelete={handleDeleteBot}
                                isSelected={selectedProspectId === prospectItem.id}
                                onCardClick={(prospect) => setSelectedProspectId(prospect.id)}
                            />
                        ))}
                        {filteredBots.length === 0 && (
                            <div className="col-span-3 text-center py-12">
                                <Bot className="w-16 h-16 text-gray-300 mx-auto mb-4" />
                                <h3 className="text-lg font-semibold text-gray-600 mb-2">No bots found</h3>
                                <p className="text-gray-500 mb-4">Adjust your filters or create a new bot to get started.</p>
                                <Button asChild className="bg-blue-600 hover:bg-blue-700">
                                    <Link to={createPageUrl('CreateRoleplayBot')}>
                                        <Plus className="w-4 h-4 mr-2" />
                                        Create New Bot
                                    </Link>
                                </Button>
                            </div>
                        )}
                    </div>
                </>
            )}

            {selectedBot && showCallModal && (
                <CallInProgress
                    prospect={selectedBot}
                    onEndCall={handleImmediateCallEnd}
                    onAnalysisComplete={handleAnalysisComplete}
                    knowledgeMaterialIds={selectedMaterials}
                />
            )}

            {botToCall && (
                 <Dialog open={showConfirmationModal} onOpenChange={setShowConfirmationModal}>
                    <DialogContent className="max-w-2xl max-h-[80vh] overflow-y-auto">
                        <DialogHeader>
                            <DialogTitle>
                                {isLeadSpecific ? `Ready to practice with ${botToCall.name}?` : `Let's get started with ${botToCall.name}`}
                            </DialogTitle>
                            <DialogDescription>
                                {isLeadSpecific ? (
                                    <>
                                        {botToCall.isLibraryPractice ?
                                            `You are about to practice a scenario from the Pitch Library. The AI will roleplay as
                                             a ${botToCall.title} from ${botToCall.company_name}, based on the provided scenario.`
                                            :
                                            `The AI will roleplay as <strong>${botToCall.name}</strong> from <strong>${botToCall.company_name}</strong>.
                                            They'll respond based on their role as ${botToCall.title} with the personality traits and pain points we've identified.`
                                        }
                                        <br/><br/>
                                        This is your chance to practice your pitch in a realistic scenario!
                                    </>
                                ) : (
                                    'At times, the bot may be unresponsive, or have unusual lag times. We are always working to improve the experience.'
                                )}
                            </DialogDescription>
                        </DialogHeader>

                        <div className="py-4 space-y-3">
                            <div className="flex items-center justify-between mb-2">
                                <div className="flex items-center gap-2">
                                    <BookOpen className="w-5 h-5 text-blue-600" />
                                    <h4 className="font-semibold text-sm">Training Materials (Optional)</h4>
                                </div>
                                <Button
                                    type="button"
                                    variant="outline"
                                    size="sm"
                                    onClick={() => {
                                        setNewMaterial({ title: '', description: '', material_type: 'document', file_url: '', content_text: '', category: 'General Training' });
                                        setUploadTab('file');
                                        setShowUploadModal(true);
                                    }}
                                >
                                    <Plus className="w-3.5 h-3.5 mr-1" />
                                    Upload
                                </Button>
                            </div>
                            <p className="text-sm text-slate-600 mb-3">
                                Upload or select materials for the AI to reference. The AI will ask questions and test your knowledge based on these.
                            </p>
                            {knowledgeMaterials.length > 0 ? (
                                <div className="space-y-2 max-h-48 overflow-y-auto border rounded-lg p-3 bg-slate-50">
                                    {knowledgeMaterials.map((material) => (
                                        <div
                                            key={material.id}
                                            className={`flex items-start gap-3 p-2 rounded transition-colors cursor-pointer ${selectedMaterials.includes(material.id) ? 'bg-blue-50 border border-blue-200' : 'hover:bg-white'}`}
                                            onClick={() => toggleMaterial(material.id)}
                                        >
                                            <Checkbox
                                                id={material.id}
                                                checked={selectedMaterials.includes(material.id)}
                                                onCheckedChange={() => toggleMaterial(material.id)}
                                            />
                                            <label htmlFor={material.id} className="flex-1 cursor-pointer">
                                                <p className="font-medium text-sm text-slate-900">{material.title}</p>
                                                <p className="text-xs text-slate-500">{material.category} • {material.material_type}</p>
                                                {material.description && (
                                                    <p className="text-xs text-slate-600 mt-1">{material.description}</p>
                                                )}
                                            </label>
                                        </div>
                                    ))}
                                </div>
                            ) : (
                                <div
                                    className="border-2 border-dashed border-gray-200 rounded-lg p-6 text-center cursor-pointer hover:border-blue-400 hover:bg-blue-50 transition-colors"
                                    onClick={() => {
                                        setNewMaterial({ title: '', description: '', material_type: 'document', file_url: '', content_text: '', category: 'General Training' });
                                        setUploadTab('file');
                                        setShowUploadModal(true);
                                    }}
                                >
                                    <BookOpen className="w-6 h-6 text-gray-400 mx-auto mb-2" />
                                    <p className="text-sm text-gray-600">No materials yet — click to upload a doc, paste text, or add a URL</p>
                                </div>
                            )}
                            {selectedMaterials.length > 0 && (
                                <p className="text-sm text-blue-600 font-medium">
                                    {selectedMaterials.length} material{selectedMaterials.length > 1 ? 's' : ''} selected
                                </p>
                            )}
                        </div>

                        <DialogFooter>
                            <Button variant="outline" onClick={() => setShowConfirmationModal(false)}>Cancel</Button>
                            <Button onClick={confirmStartCall} className="bg-blue-600 hover:bg-blue-700">
                                {isLeadSpecific ? 'Start Pitch Practice' : 'I understand, start call'}
                            </Button>
                        </DialogFooter>
                    </DialogContent>
                </Dialog>
            )}

            {showUploadModal && (
                <Dialog open={showUploadModal} onOpenChange={setShowUploadModal}>
                    <DialogContent className="max-w-lg">
                        <DialogHeader>
                            <DialogTitle>Add Training Material</DialogTitle>
                        </DialogHeader>
                        <div className="space-y-4">
                            <Tabs value={uploadTab} onValueChange={setUploadTab}>
                                <TabsList className="grid grid-cols-3 w-full">
                                    <TabsTrigger value="file">File</TabsTrigger>
                                    <TabsTrigger value="url">URL</TabsTrigger>
                                    <TabsTrigger value="text">Text</TabsTrigger>
                                </TabsList>
                                <TabsContent value="file" className="mt-3">
                                    <div
                                        className={`border-2 border-dashed rounded-xl p-8 text-center transition-colors cursor-pointer ${isDragging ? 'border-blue-500 bg-blue-50' : 'border-gray-200 hover:border-blue-400'}`}
                                        onDragOver={(e) => { e.preventDefault(); setIsDragging(true); }}
                                        onDragLeave={() => setIsDragging(false)}
                                        onDrop={(e) => { e.preventDefault(); setIsDragging(false); const f = e.dataTransfer.files[0]; if (f) handleFileUpload(f); }}
                                        onClick={() => fileInputRef.current?.click()}
                                    >
                                        {isUploading ? (
                                            <div className="flex flex-col items-center gap-2"><Loader2 className="w-8 h-8 text-blue-600 animate-spin" /><p className="text-sm text-muted-foreground">Uploading...</p></div>
                                        ) : newMaterial.file_url && uploadTab === 'file' ? (
                                            <div className="flex flex-col items-center gap-2"><CheckCircle className="w-8 h-8 text-green-600" /><p className="text-sm font-medium text-green-700">Uploaded — click to replace</p></div>
                                        ) : (
                                            <>
                                                <BookOpen className="w-8 h-8 text-gray-400 mx-auto mb-2" />
                                                <p className="font-medium text-gray-700">Drop file here or click to browse</p>
                                                <p className="text-xs text-muted-foreground mt-1">PDF, DOC, DOCX, TXT, MP4, MP3, WAV — up to 50MB</p>
                                            </>
                                        )}
                                    </div>
                                    <input ref={fileInputRef} type="file" className="hidden" accept=".pdf,.doc,.docx,.txt,.mp4,.mp3,.wav,.m4a,.mov" onChange={(e) => { const f = e.target.files?.[0]; if (f) handleFileUpload(f); }} />
                                </TabsContent>
                                <TabsContent value="url" className="mt-3">
                                    <div className="space-y-2">
                                        <Label>Document or Video URL</Label>
                                        <Input placeholder="https://..." value={newMaterial.file_url} onChange={(e) => setNewMaterial(prev => ({ ...prev, file_url: e.target.value }))} />
                                        <p className="text-xs text-muted-foreground">Link to a publicly accessible file</p>
                                    </div>
                                </TabsContent>
                                <TabsContent value="text" className="mt-3">
                                    <div className="space-y-2">
                                        <Label>Content</Label>
                                        <Textarea placeholder="Paste your training content, product info, scripts, FAQs..." rows={5} value={newMaterial.content_text} onChange={(e) => setNewMaterial(prev => ({ ...prev, content_text: e.target.value, material_type: 'text' }))} />
                                        <p className="text-xs text-muted-foreground">The AI will use this as its knowledge base</p>
                                    </div>
                                </TabsContent>
                            </Tabs>
                            <div className="space-y-3 pt-2 border-t">
                                <div>
                                    <Label>Title *</Label>
                                    <Input placeholder="e.g., Product Overview Q2" value={newMaterial.title} onChange={(e) => setNewMaterial(prev => ({ ...prev, title: e.target.value }))} />
                                </div>
                                <div className="grid grid-cols-2 gap-3">
                                    <div>
                                        <Label>Category</Label>
                                        <Select value={newMaterial.category} onValueChange={(v) => setNewMaterial(prev => ({ ...prev, category: v }))}>
                                            <SelectTrigger><SelectValue /></SelectTrigger>
                                            <SelectContent>{MATERIAL_CATEGORIES.map(c => <SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent>
                                        </Select>
                                    </div>
                                    <div>
                                        <Label>Type</Label>
                                        <Select value={newMaterial.material_type} onValueChange={(v) => setNewMaterial(prev => ({ ...prev, material_type: v }))}>
                                            <SelectTrigger><SelectValue /></SelectTrigger>
                                            <SelectContent>
                                                <SelectItem value="document">Document</SelectItem>
                                                <SelectItem value="video">Video</SelectItem>
                                                <SelectItem value="audio">Audio</SelectItem>
                                                <SelectItem value="text">Text</SelectItem>
                                            </SelectContent>
                                        </Select>
                                    </div>
                                </div>
                            </div>
                            <div className="flex justify-end gap-2 pt-2">
                                <Button type="button" variant="outline" onClick={() => setShowUploadModal(false)}>Cancel</Button>
                                <Button type="button" onClick={handleSaveMaterial} disabled={isUploading}>
                                    {isUploading ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <CheckCircle className="w-4 h-4 mr-2" />}
                                    Save & Select
                                </Button>
                            </div>
                        </div>
                    </DialogContent>
                </Dialog>
            )}
        </div>
    );
}
